[features]
seeds = false
skip-lint = false

[programs.localnet]
asdf_dat = "ASDfNfUHwVGfrg3SV7SQYWhaVxnrCUZyWmMpWJAPu4MZ"

[programs.devnet]
asdf_dat = "ASDfNfUHwVGfrg3SV7SQYWhaVxnrCUZyWmMpWJAPu4MZ"

[programs.mainnet]
asdf_dat = "ASDfNfUHwVGfrg3SV7SQYWhaVxnrCUZyWmMpWJAPu4MZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./mainnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"